FROM python:3.11-slim

WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install pytest pytest-asyncio httpx python-dotenv

CMD ["pytest", "-v", "tests/"]
